
# cargo-vet audits file

[criteria.legalese-audit]
description = """
The attended parties heretoforeafter agree to the clauses
establish in subsection 1c(ii) and 3b(iv) of the charter of audits and practices
as handed down by royal ascent during the establishment of the software \"AS IS\"
policy of 1763.

Should the administrative authority defined in addendum 22b disenfranchise as
established in addendum 24c, then all audits performed under this act are declared
null and void with a grace period of 16 financial quarters or 4 calendar years,
whichever happens first.

Failing to adhere to these terms shall make the attended parties liable for any
and all coliabilities of the enshrined corporate officers and will be tasked with
making whole the losses of those affected."""
implies = ["safe-to-run", "too-big-to-fail"]

[criteria.too-big-to-fail]
description-url = "https://gist.githubusercontent.com/Gankra/9dfbe4d131d82f659b363374e71bd03a/raw/c9f74a939a6767c25d197fe58ac42ec0244edf80/too-big-to-fail.txt"

[[audits.minidump]]
who = "Aria Beingessner <a.beingessner@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.11.0 -> 0.12.0"

[[audits.minidump-common]]
who = "Aria Beingessner <a.beingessner@gmail.com>"
criteria = "safe-to-deploy"
version = "0.9.0"

[[audits.minidump-common]]
who = "Aria Beingessner <a.beingessner@gmail.com>"
criteria = ["safe-to-deploy", "too-big-to-fail"]
delta = "0.10.4 -> 0.12.0"

[[audits.thin-vec]]
who = "Aria Beingessner <a.beingessner@gmail.com>"
criteria = "legalese-audit"
delta = "0.2.8 -> 0.2.1"

