
# cargo-vet config file

[[exemptions.adler]]
version = "1.0.2"
criteria = "safe-to-deploy"

[[exemptions.async-compression]]
version = "0.3.15"
criteria = "safe-to-deploy"

[[exemptions.atty]]
version = "0.2.14"
criteria = "safe-to-deploy"

[[exemptions.autocfg]]
version = "1.1.0"
criteria = "safe-to-deploy"

[[exemptions.base64]]
version = "0.13.0"
criteria = "safe-to-deploy"

[[exemptions.bitflags]]
version = "1.3.2"
criteria = "safe-to-deploy"

[[exemptions.bumpalo]]
version = "3.11.0"
criteria = "safe-to-deploy"

[[exemptions.bytes]]
version = "1.2.1"
criteria = "safe-to-deploy"

[[exemptions.cc]]
version = "1.0.73"
criteria = "safe-to-deploy"

[[exemptions.cfg-if]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.clap]]
version = "4.0.15"
criteria = "safe-to-deploy"

[[exemptions.clap_lex]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.crc32fast]]
version = "1.3.2"
criteria = "safe-to-deploy"

[[exemptions.encoding_rs]]
version = "0.8.31"
criteria = "safe-to-deploy"

[[exemptions.flate2]]
version = "1.0.24"
criteria = "safe-to-deploy"

[[exemptions.fnv]]
version = "1.0.7"
criteria = "safe-to-deploy"

[[exemptions.form_urlencoded]]
version = "1.1.0"
criteria = "safe-to-deploy"

[[exemptions.futures-channel]]
version = "0.3.24"
criteria = "safe-to-deploy"

[[exemptions.futures-core]]
version = "0.3.24"
criteria = "safe-to-deploy"

[[exemptions.futures-sink]]
version = "0.3.24"
criteria = "safe-to-deploy"

[[exemptions.futures-task]]
version = "0.3.24"
criteria = "safe-to-deploy"

[[exemptions.futures-util]]
version = "0.3.24"
criteria = "safe-to-deploy"

[[exemptions.h2]]
version = "0.3.14"
criteria = "safe-to-deploy"

[[exemptions.hashbrown]]
version = "0.12.3"
criteria = "safe-to-deploy"

[[exemptions.hermit-abi]]
version = "0.1.19"
criteria = "safe-to-deploy"

[[exemptions.http]]
version = "0.2.8"
criteria = "safe-to-deploy"

[[exemptions.http-body]]
version = "0.4.5"
criteria = "safe-to-deploy"

[[exemptions.httparse]]
version = "1.8.0"
criteria = "safe-to-deploy"

[[exemptions.httpdate]]
version = "1.0.2"
criteria = "safe-to-deploy"

[[exemptions.hyper]]
version = "0.14.20"
criteria = "safe-to-deploy"

[[exemptions.hyper-rustls]]
version = "0.23.0"
criteria = "safe-to-deploy"

[[exemptions.idna]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.indexmap]]
version = "1.9.1"
criteria = "safe-to-deploy"

[[exemptions.ipnet]]
version = "2.5.0"
criteria = "safe-to-deploy"

[[exemptions.itoa]]
version = "1.0.4"
criteria = "safe-to-deploy"

[[exemptions.js-sys]]
version = "0.3.60"
criteria = "safe-to-deploy"

[[exemptions.libc]]
version = "0.2.135"
criteria = "safe-to-deploy"

[[exemptions.log]]
version = "0.4.17"
criteria = "safe-to-deploy"

[[exemptions.memchr]]
version = "2.5.0"
criteria = "safe-to-deploy"

[[exemptions.mime]]
version = "0.3.16"
criteria = "safe-to-deploy"

[[exemptions.miniz_oxide]]
version = "0.5.4"
criteria = "safe-to-deploy"

[[exemptions.mio]]
version = "0.8.4"
criteria = "safe-to-deploy"

[[exemptions.once_cell]]
version = "1.15.0"
criteria = "safe-to-deploy"

[[exemptions.os_str_bytes]]
version = "6.3.0"
criteria = "safe-to-deploy"

[[exemptions.percent-encoding]]
version = "2.2.0"
criteria = "safe-to-deploy"

[[exemptions.pin-project-lite]]
version = "0.2.9"
criteria = "safe-to-deploy"

[[exemptions.pin-utils]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.proc-macro2]]
version = "1.0.46"
criteria = "safe-to-deploy"

[[exemptions.quote]]
version = "1.0.21"
criteria = "safe-to-deploy"

[[exemptions.reqwest]]
version = "0.11.12"
criteria = "safe-to-deploy"

[[exemptions.ring]]
version = "0.16.20"
criteria = "safe-to-deploy"

[[exemptions.rustls]]
version = "0.20.6"
criteria = "safe-to-deploy"

[[exemptions.rustls-pemfile]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.ryu]]
version = "1.0.11"
criteria = "safe-to-deploy"

[[exemptions.sct]]
version = "0.7.0"
criteria = "safe-to-deploy"

[[exemptions.serde]]
version = "1.0.145"
criteria = "safe-to-deploy"

[[exemptions.serde_derive]]
version = "1.0.145"
criteria = "safe-to-deploy"

[[exemptions.serde_json]]
version = "1.0.86"
criteria = "safe-to-deploy"

[[exemptions.serde_urlencoded]]
version = "0.7.1"
criteria = "safe-to-deploy"

[[exemptions.slab]]
version = "0.4.7"
criteria = "safe-to-deploy"

[[exemptions.socket2]]
version = "0.4.7"
criteria = "safe-to-deploy"

[[exemptions.spin]]
version = "0.5.2"
criteria = "safe-to-deploy"

[[exemptions.strsim]]
version = "0.10.0"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "1.0.102"
criteria = "safe-to-deploy"

[[exemptions.termcolor]]
version = "1.1.3"
criteria = "safe-to-deploy"

[[exemptions.tinyvec]]
version = "1.6.0"
criteria = "safe-to-deploy"

[[exemptions.tinyvec_macros]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.tokio]]
version = "1.21.2"
criteria = "safe-to-deploy"

[[exemptions.tokio-rustls]]
version = "0.23.4"
criteria = "safe-to-deploy"

[[exemptions.tokio-util]]
version = "0.7.4"
criteria = "safe-to-deploy"

[[exemptions.tower-service]]
version = "0.3.2"
criteria = "safe-to-deploy"

[[exemptions.tracing]]
version = "0.1.37"
criteria = "safe-to-deploy"

[[exemptions.tracing-core]]
version = "0.1.30"
criteria = "safe-to-deploy"

[[exemptions.try-lock]]
version = "0.2.3"
criteria = "safe-to-deploy"

[[exemptions.unicode-bidi]]
version = "0.3.8"
criteria = "safe-to-deploy"

[[exemptions.unicode-ident]]
version = "1.0.5"
criteria = "safe-to-deploy"

[[exemptions.unicode-normalization]]
version = "0.1.22"
criteria = "safe-to-deploy"

[[exemptions.untrusted]]
version = "0.7.1"
criteria = "safe-to-deploy"

[[exemptions.url]]
version = "2.3.1"
criteria = "safe-to-deploy"

[[exemptions.want]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.wasi]]
version = "0.11.0+wasi-snapshot-preview1"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen]]
version = "0.2.83"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-backend]]
version = "0.2.83"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-futures]]
version = "0.4.33"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro]]
version = "0.2.83"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro-support]]
version = "0.2.83"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-shared]]
version = "0.2.83"
criteria = "safe-to-deploy"

[[exemptions.web-sys]]
version = "0.3.60"
criteria = "safe-to-deploy"

[[exemptions.webpki]]
version = "0.22.0"
criteria = "safe-to-deploy"

[[exemptions.webpki-roots]]
version = "0.22.5"
criteria = "safe-to-deploy"

[[exemptions.winapi]]
version = "0.3.9"
criteria = "safe-to-deploy"

[[exemptions.winapi-i686-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.winapi-util]]
version = "0.1.5"
criteria = "safe-to-deploy"

[[exemptions.winapi-x86_64-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.windows-sys]]
version = "0.36.1"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_msvc]]
version = "0.36.1"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnu]]
version = "0.36.1"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_msvc]]
version = "0.36.1"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnu]]
version = "0.36.1"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_msvc]]
version = "0.36.1"
criteria = "safe-to-deploy"

[[exemptions.winreg]]
version = "0.10.1"
criteria = "safe-to-deploy"

