name: Certify Dependencies
on:
  workflow_dispatch:
    inputs:
      audits:
        description: "a Base64-encoded JSON blob of the audits to certify"
        required: true
  # push:
  #  branches:
  #  - main
  # pull_request:
jobs:
  cargo-vet-certify:
    name: Vet Dependencies
    runs-on: ubuntu-latest
    env:
      # Token required to submit comments on failed PRs
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CARGO_VET_VERSION: 0.3.0
      VET_FAILURE_SUBMIT_ENDPOINT: https://cargo-vet.axo.dev/api/webhooks/receive
      VET_FAILURE_VIEW_ENDPOINT: https://cargo-vet.axo.dev/reports
      VET_RESULTS_FILE: vet-results.json
      VET_RESULTS_FILE_FINAL: vet-results-final.json
    steps:
    - name: Log Audits
      run: |
        echo "certifying with these audits:"
        decoded=$(echo ${{ needs.get-audits.outputs.audits }} | base64 --decode)
        echo $decoded
    - uses: actions/checkout@master
    - name: Install Rust
      run: rustup update stable && rustup default stable
    - uses: actions/cache@v2
      with:
        path: ${{ runner.tool_cache }}/cargo-vet
        key: cargo-vet-bin-${{ env.CARGO_VET_VERSION }}
    - name: Add the tool cache directory to the search path
      run: echo "${{ runner.tool_cache }}/cargo-vet/bin" >> $GITHUB_PATH
    - name: Ensure that the tool cache is populated with the cargo-vet binary
      # run: cargo install --root ${{ runner.tool_cache }}/cargo-vet --version ${{ env.CARGO_VET_VERSION }} cargo-vet
      # Currently patching in a fork
      run: cargo install --root ${{ runner.tool_cache }}/cargo-vet --version ${{ env.CARGO_VET_VERSION }} --git https://github.com/Gankra/cargo-vet --branch bots cargo-vet
    - name: Apply New Audits
      uses: ./.github/workflows/certify
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        audits: ${{ inputs.audits }}
