name: Vet Dependencies
on: 
  # push:
  #  branches:
  #    - main
  pull_request:
jobs:
  cargo-vet-check:
      name: Vet Dependencies
      runs-on: ubuntu-latest
      env:
        # Token required to submit comments on failed PRs
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CARGO_VET_VERSION: 0.3.0
        VET_RESULTS_FILE: vet-results.json
        ARTIFACTS_DIR: pr
      steps:
      - uses: actions/checkout@master
      - name: Install Rust
        run: rustup update stable && rustup default stable
      - uses: actions/cache@v2
        with:
          path: ${{ runner.tool_cache }}/cargo-vet
          key: cargo-vet-bin-${{ env.CARGO_VET_VERSION }}
      - name: Add the tool cache directory to the search path
        run: echo "${{ runner.tool_cache }}/cargo-vet/bin" >> $GITHUB_PATH
      - name: Ensure that the tool cache is populated with the cargo-vet binary
        # run: cargo install --root ${{ runner.tool_cache }}/cargo-vet --version ${{ env.CARGO_VET_VERSION }} cargo-vet
        # Currently patching in a fork
        run: cargo install --root ${{ runner.tool_cache }}/cargo-vet --version ${{ env.CARGO_VET_VERSION }} --git https://github.com/Gankra/cargo-vet --branch bots cargo-vet
      - name: Invoke cargo-vet
        # Currently emitting a custom output
        run: |
          mkdir -p ./${{ env.ARTIFACTS_DIR }}
          cargo vet --locked --output-format=json-full > ./${{ env.ARTIFACTS_DIR }}/${{ env.VET_RESULTS_FILE }}
          # run: cargo vet --locked --output-format=json > ./${{ env.ARTIFACTS_DIR }}/${{ env.VET_RESULTS_FILE }}
      - if: ${{ failure() }}
        name: Log Failure
        run: cat ./pr/${{ env.VET_RESULTS_FILE }}
      - if: ${{ failure() && github.event.pull_request.number }}
        # TODO: only do this if "Invoke cargo-vet" was the step that failed?
        # Is that guaranteed by all the previous steps not being gated on failure()?
        # Or will any of their failures "fall through" to this one?
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ARTIFACTS_DIR }}
          path: ${{ env.ARTIFACTS_DIR }}/

          

