# The "Normal" CI for tests and linters and whatnot
name: Rust CI

# Ci should be run on...
on:
  # Every pull request (will need approval for new contributors)
  pull_request:
  # Every push to...
  push:
    branches:
      # The main branch
      - main
      # Not a thing I use personally but some people like having a release branch
      - "release/**"
  # And once a week? 
  # This can catch things like "rust updated and actually regressed something"
  schedule:
    - cron: "11 7 * * 1,4"

# We want all these checks to fail if they spit out warnings
env:
  RUSTFLAGS: -Dwarnings

jobs:
  # Check that rustfmt is a no-op
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: rustfmt
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  # Check that clippy is appeased
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: clippy
          override: true
      - uses: actions-rs/clippy-check@v1
        env:
          PWD: ${{ env.GITHUB_WORKSPACE }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --workspace --tests --examples

  # Make sure the docs build without warnings
  docs:
    runs-on: ubuntu-latest
    env:
      RUSTDOCFLAGS: -Dwarnings
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: rust-docs
          override: true
      - uses: swatinem/rust-cache@v1
      - uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --workspace --no-deps

  # Run cargo-vet (taken from the cargo-vet book)
  cargo-vet:
    name: Vet Dependencies
    runs-on: ubuntu-latest
    env:
      CARGO_VET_VERSION: 0.3.0
    steps:
    - uses: actions/checkout@master
    - name: Install Rust
      run: rustup update stable && rustup default stable
    - uses: actions/cache@v2
      with:
        path: ${{ runner.tool_cache }}/cargo-vet
        key: cargo-vet-bin-${{ env.CARGO_VET_VERSION }}
    - name: Add the tool cache directory to the search path
      run: echo "${{ runner.tool_cache }}/cargo-vet/bin" >> $GITHUB_PATH
    - name: Ensure that the tool cache is populated with the cargo-vet binary
      # Currently patching in a fork
      run: cargo install --root ${{ runner.tool_cache }}/cargo-vet --version ${{ env.CARGO_VET_VERSION }} --git https://github.com/Gankra/cargo-vet --branch bots cargo-vet
    - name: Invoke cargo-vet
      # Currently emitting a custom output
      run: cargo vet --locked --output-format=json-full

  # Build and run tests/doctests/examples on all platforms
  # probe all your features and rust versions (see tracing's ci)
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      # Test the cross-product of these platforms+toolchains
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [nightly, stable]
    steps:
      # Setup tools
      - uses: actions/checkout@master
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
          override: true
      - uses: swatinem/rust-cache@v1
      # Run the tests/doctests (default features)
      - uses: actions-rs/cargo@v1
        env:
          PWD: ${{ env.GITHUB_WORKSPACE }}
        with:
          command: test
          args: --workspace
      # Run the tests/doctests (all features)
      - uses: actions-rs/cargo@v1
        env:
          PWD: ${{ env.GITHUB_WORKSPACE }}
        with:
          command: test
          args: --workspace --all-features
      # Test the examples (default features)
      - uses: actions-rs/cargo@v1
        env:
          PWD: ${{ env.GITHUB_WORKSPACE }}
        with:
          command: test
          args: --workspace --examples --bins
      # Test the examples (all features)
      - uses: actions-rs/cargo@v1
        env:
          PWD: ${{ env.GITHUB_WORKSPACE }}
        with:
          command: test
          args: --workspace --all-features --examples --bins